"""
StudyOS DB Models — Study Plan.

Responsibility: Defines the SQLAlchemy ORM models for the `study_plan` 
and `study_task` tables.
Contains no business logic, only the schema definition and relationships.
"""

from datetime import datetime, timezone
from sqlalchemy import String, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base


class StudyPlan(Base):
    """
    Represents an AI-generated study schedule for a user.
    
    Attributes:
        id: Primary key.
        user_id: Foreign key linking to the student.
        title: Descriptive title of the plan (e.g., 'Midterm Prep').
        status: Progress state ('active', 'completed', 'abandoned').
        created_at: Timestamp of creation (UTC).
    """
    __tablename__ = "study_plan"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[str] = mapped_column(String(50), default="active")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    
    user: Mapped["User"] = relationship("User", back_populates="study_plans")
    
    # A study plan consists of many scheduled tasks
    tasks: Mapped[list["StudyTask"]] = relationship(
        "StudyTask", back_populates="plan", cascade="all, delete-orphan"
    )


class StudyTask(Base):
    """
    Represents an actionable item or topic scheduled within a StudyPlan.
    
    Attributes:
        id: Primary key.
        plan_id: Foreign key linking to the parent StudyPlan.
        title: The topic or action to complete.
        description: Detailed instructions generated by AI.
        scheduled_date: When the student should perform this task.
        completed: Boolean toggle tracking progress.
    """
    __tablename__ = "study_task"

    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    plan_id: Mapped[int] = mapped_column(ForeignKey("study_plan.id"), index=True, nullable=False)
    
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    scheduled_date: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    completed: Mapped[bool] = mapped_column(Boolean, default=False)
    
    # ── Relationships ─────────────────────────────────────────────────────────
    
    plan: Mapped["StudyPlan"] = relationship("StudyPlan", back_populates="tasks")
